version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Optional: sync local changes without rebuilding
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development  # Optional: enables debug mode
